language: node_js
node_js:
  - '4'

env:
  global:
    - ENCRYPTION_LABEL: "aa286ccd339e"
    - COMMIT_AUTHOR_EMAIL: "patternfly-build@redhat.com"
    - TRIGGER_REPO_SLUG: "patternfly/angular-patternfly"
    - TRIGGER_REPO_BRANCH: "master"

before_install:
  - 'git checkout -B $TRAVIS_BRANCH' # Reconcile detached HEAD
  - 'npm install -g bower grunt-cli'

script:
  - sh -x ./scripts/build.sh

after_success:
  - ./scripts/publish-ghpages.sh -t docs

# OpenShift expects its deployment branch to be "master-dist". This can be changed using:
# rhc app-configure patternfly/angular --deployment-branch master-dist
deploy:
  provider: openshift
  user: "$OPENSHIFT_USER"
  password: "$OPENSHIFT_PWD"
  domain: "patternfly"
  app: angular
  skip_cleanup: true
  on: # The branch and repo that triggered the build
    branch: master
    condition: $TRAVIS_REPO_SLUG = "patternfly/angular-patternfly"
